name: Running Away Balloon
source: https://knowyourmeme.com/memes/running-away-balloon
keywords:
  - Superlmer
text:
  - style: upper
    color: black
    font: comic
    anchor_x: 0.61
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.39
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: comic
    anchor_x: 0.8
    anchor_y: 0.57
    angle: 0.0
    scale_x: 0.39
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: comic
    anchor_x: 0.0
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.27
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - Opportunities
  - Opportunities
  - Shyness
overlay:
  - center_x: 0.82
    center_y: 0.2
    angle: 0.0
    scale: 0.35
  - center_x: 0.965
    center_y: 0.67
    angle: 0.0
    scale: 0.3
  - center_x: 0.13
    center_y: 0.81
    angle: 0.0
    scale: 0.235
