from . import static
from . import root
from . import templates
from . import links
from . import image
from . import overview
from . import generator
from . import latest
from . import future
from . import aliases
from . import magic
