name: Two Guys on a Bus
source: https://knowyourmeme.com/memes/two-guys-on-a-bus
keywords:
  - Genildo Ronchi
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.25
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.16
    angle: 0.0
    scale_x: 0.4
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
example:
  - Postseason
  - Preseason
overlay:
  - center_x: 0.18
    center_y: 0.3
    angle: 0.0
    scale: 0.4
  - center_x: 0.7
    center_y: 0.22
    angle: 0.0
    scale: 0.4
